#!/bin/bash

echo "🚀 Guide de déploiement de l'API sur Render"
echo "============================================"
echo ""

echo "📋 Checklist avant déploiement:"
echo ""
echo "✅ 1. Code committé sur GitHub"
echo "✅ 2. Repository public ou Render connecté"
echo "✅ 3. Dockerfile et render.yaml présents"
echo ""

echo "🌐 Étapes de déploiement:"
echo ""
echo "1️⃣  Aller sur https://render.com et se connecter"
echo ""
echo "2️⃣  Créer une base de données PostgreSQL:"
echo "   → Dashboard > New +"
echo "   → PostgreSQL"
echo "   → Name: pokedex-db"
echo "   → Database: pokedex"
echo "   → User: pokedex_user"
echo "   → Cliquer sur 'Create Database'"
echo ""
echo "   📝 Noter les credentials:"
echo "   - Internal Database URL"
echo "   - Hostname"
echo "   - Port: 5432"
echo "   - Database: pokedex"
echo "   - Username: pokedex_user"
echo "   - Password: (généré automatiquement)"
echo ""

echo "3️⃣  Créer le Web Service:"
echo "   → Dashboard > New +"
echo "   → Web Service"
echo "   → Connect GitHub repository: pokedex-vue"
echo "   → Name: pokedex-api"
echo "   → Root Directory: pokedex-api"
echo "   → Environment: Go"
echo "   → Build Command: go build -o main ."
echo "   → Start Command: ./main"
echo "   → Instance Type: Free (ou Starter \$7/mois)"
echo ""

echo "4️⃣  Configurer les variables d'environnement:"
echo "   → Environment tab"
echo "   → Add Environment Variable"
echo ""
echo "   Variables à ajouter:"
echo ""
echo "   DB_HOST=<hostname de PostgreSQL>"
echo "   POSTGRES_DB=pokedex"
echo "   POSTGRES_USER=pokedex_user"
echo "   POSTGRES_PASSWORD=<password de PostgreSQL>"
echo "   POSTGRES_PORT=5432"
echo "   JWT_SECRET=\$(openssl rand -base64 32)"
echo "   GIN_MODE=release"
echo "   API_PORT=8080"
echo ""

echo "5️⃣  Déployer:"
echo "   → Cliquer sur 'Create Web Service'"
echo "   → Attendre le déploiement (3-5 minutes)"
echo "   → Vérifier les logs"
echo ""

echo "6️⃣  Tester l'API:"
echo "   → URL: https://pokedex-api-xxxx.onrender.com"
echo "   → Test: https://pokedex-api-xxxx.onrender.com/api/register"
echo ""

echo "7️⃣  Mettre à jour le frontend:"
echo "   → Modifier pokedex-vue/.env.production"
echo "   → VITE_API_URL=https://votre-api.onrender.com"
echo "   → Commit et push"
echo ""

echo "============================================"
echo ""
echo "💡 Commandes utiles:"
echo ""
echo "# Générer JWT secret"
echo "openssl rand -base64 32"
echo ""
echo "# Tester l'API en local"
echo "cd pokedex-api && make up"
echo ""
echo "# Voir les logs Render"
echo "Dashboard > Service > Logs (temps réel)"
echo ""

echo "============================================"
echo ""
echo "📚 Documentation complète: DEPLOYMENT.md"
echo "🆘 Support: https://github.com/HeckoDev/pokedex-vue/issues"
echo ""
